/*
 * Auth
 */
export const SET_AUTH_STATUS = 'SET_AUTH_STATUS';
export const REQUEST_SIGNUP = 'REQUEST_SIGNUP';
export const REQUEST_SIGNIN = 'REQUEST_SIGNIN';
export const REQUEST_SIGNOUT = 'REQUEST_SIGNOUT';
export const REQUEST_UPDATE_PASSWORD = 'REQUEST_UPDATE_PASSWORD';
export const REQUEST_RESET_PASSWORD = 'REQUEST_RESET_PASSWORD';
export const REQUEST_UPDATE_USER_INFO = 'REQUEST_UPDATE_USER_INFO';

/*
 * Travel Details
 */
export const REQUEST_CHANGE_TRAVEL_DETAILS = 'REQUEST_CHANGE_TRAVEL_DETAILS';

/*
 * Residency Details
 */
export const REQUEST_CHANGE_RESIDENCY_DETAILS =
  'REQUEST_CHANGE_RESIDENCY_DETAILS';

/*
 * Country Picker
 */
export const TOGGLE_SELECTED_COUNTRY = 'TOGGLE_SELECTED_COUNTRY';

/*
 * City Picker
 */
export const TOGGLE_SELECTED_CITY = 'TOGGLE_SELECTED_CITY';

/*
 * DB
 */
export const REFRESH_STORE_WITH_DB_DATA_SUCCESS =
  'REFRESH_STORE_WITH_DB_DATA_SUCCESS';
export const REFRESH_STORE_WITH_DB_DATA_FAIL =
  'REFRESH_STORE_WITH_DB_DATA_FAIL';

/*
 * Sync
 */
export const REQUEST_SYNC = 'REQUEST_SYNC';
